name: CI

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: make dev-deps
      - name: Run lint checks
        run: make lint
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: make dev-deps
      - name: Run type checks
        run: make mypy
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: make dev-deps
      - name: Run tests
        run: make test
